language: php

env:
  - PHALCON_VERSION="2.0.0"

php:
  - 5.4
  - 5.5

before_script:
  - mysql < robots.sql
  - sed -s 's/https:\/\/phalcon-rest-travis-vytorcalixto.c9.io/http:\/\/localhost/' -i tests/*
  - sed -s 's/getenv("IP")/"localhost"/' -i index.php
  - sed -s 's/"vytorcalixto"/"root"/' -i index.php
  - chmod +x ./tests/install-php-extension.sh
  - ./tests/install-php-extension.sh ${PHALCON_VERSION}
  - php -r 'echo \Phalcon\Version::get()."\n";'
  - composer self-update
  - composer install
  - php -i | grep phalcon